[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
num_cpus = "1.14"
bson = "2.5.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
sha2 = "0.10.6"
rand = "0.8.5"
hex = "0.4.3"
tiny_http = "0.11"